config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :routines
  resources :users
  resources :splits
  resources :comments
  
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions', to: 'sessions#create', as: 'login'
  delete '/sessions', to: 'sessions#destroy', as: 'logout'

  get '/about', to: 'routines#about', as: 'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :routine
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    has_many :splits
    has_many :routines, through: :splits
end

app/models/routine.rb
class Routine < ApplicationRecord
    belongs_to :user 
    has_many :comments
    has_many :users, through: :comments
    has_many :splits
    has_many :exercises, through: :splits
end

app/models/scraper.rb
require 'nokogiri'
require 'httparty'
require 'byebug'

class Scraper
 
    def self.workout_info
        url = "https://www.self.com/gallery/bodyweight-exercises-you-can-do-at-home"
        unparsed_page = HTTParty.get(url)
            #get request for the url you would like to scrape
        parsed_page = Nokogiri::HTML(unparsed_page)
            #Nokogiri parses the HTML of the entire page from the url 

        workout_text = parsed_page.css('div.gallery-slide-caption')
            #workout_text is an array of data for all 53 workouts

        workout_array = []
            #create an empty array to push in only the info you want

        workout_text.each do |workout|
            #this loop goes through all 53 divs holding the workout container and 
            #adds the text we want as the value to our :name and :description keys
            text = {
                name: workout.css('h2.gallery-slide-caption__hed').text,
                description: workout.css('div.gallery-slide-caption__dek').text
            }
            workout_array << text
            #for each div of information we are pushing the "text" hash into our workout_array
        end
        workout_array 
            #workout_array holds an array of hashs for all 53 workouts with name and description keys
    end 
    
end

app/models/split.rb
class Split < ApplicationRecord
    belongs_to :exercise
    belongs_to :routine
end

app/models/user.rb
class User < ApplicationRecord
    has_many :routines
    has_many :comments
    has_many :splits, through: :routines

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_user
    before_action :authorized
  
    def set_user
      @logged_in_user = User.find_by(id: session[:user_id])
    end 
  
    def authorized
      if @logged_in_user
      else
        flash[:errors] = "Please Log-in"
        redirect_to routines_path
      end 
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @logged_in_user.comments << Comment.create(comment_params)
        redirect_to routine_path(comment_params[:routine_id])
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to routine_path(@comment.routine)
    end

    private 

    def comment_params
        params.require(:comment).permit(:comment, :routine_id)
    end 
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    skip_before_action :authorized, only: [:index, :show]

    def index
        @exercises = Exercise.all
    end

    def show
        @exercise = Exercise.find(params[:id])
        if @logged_in_user
            @routines = Routine.where({:user_id => @logged_in_user.id})
            @split = Split.new
        end
    end

end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
    skip_before_action :authorized, only: [:index, :show, :about]
    before_action :find_routine, only: [:show, :edit, :update, :destroy]
    before_action :weekdays, only: [:new, :edit]
    
    def index
        @routines = Routine.all
    end

    def new
        @users = User.all
        @routine = Routine.new
    end

    def create
        @new_routine = @logged_in_user.routines.create(routine_params)
        # if @routine.valid?
        redirect_to routine_path(@new_routine)
        # end
    end
    
    def edit
        @users = User.all
    end
    
    def update
         @routine.update(routine_params)

         redirect_to routine_path(@routine)
    end

    def show
         #@routine = Routine.find(params[:id])
         @comment = Comment.new
         #for the add exercise (split) form
         @split = Split.new
         @exercises = Exercise.all
    end
    
    def destroy
        @routine.destroy
        redirect_to routines_path
    end

    def about 
        render :about
    end 

    private

    def find_routine
        @routine = Routine.find(params[:id])
    end

    def routine_params
        params.require(:routine).permit(:name, :weekday)
    end

    def weekdays
        @weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]

    def create 
        user = User.find_by(name: session_params[:name])

        if user && user.authenticate(session_params[:password])
            session[:user_id] = user.id
            redirect_to user
        else
            flash[:errors] = "Try Again"
            redirect_to new_login_path
        end
    end

    def destroy 
        session[:user_id] = nil
        redirect_to routines_path
    end

    private 

    def session_params
        params.require(:session).permit(:name, :password)
    end
end

app/controllers/splits_controller.rb
class SplitsController < ApplicationController

    def new
        @split = Split.new
        @routines = Routine.where({:user_id => @logged_in_user.id})
        @exercises = Exercise.all
    end

    def create
        @split = Split.create(split_params)
        redirect_to routine_path(split_params[:routine_id])
    end

    def edit
        @split = Split.find(params[:id])
        @routines = Routine.where({:user_id => @logged_in_user.id})
        @exercises = Exercise.all
    end

    def update
        @split = Split.find(params[:id])
        @split.update(split_params)
        redirect_to routine_path(split_params[:routine_id])
    end

    def destroy
        @split = Split.find(params[:id])
        @split.destroy
        redirect_to routine_path(@split.routine)
    end

    private 

    def split_params
        params.require(:split).permit(:routine_id, :exercise_id, :duration)
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:create, :new]

  def show 
    @user = User.find(params[:id])

    if @user == @logged_in_user
      render :show 
    else
        redirect_to new_login_path
    end 
  end 

  def new 
    @user = User.new
  end 

  def create 
    user = User.create(user_params)

    if user.valid? 
      session[:user_id] = user.id
      redirect_to user
    else 
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :password)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/splits_helper.rb
module SplitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weekdays_helper.rb
module WeekdaysHelper
end

app/views/exercises/_nav.html.erb
<h1 class="web_name">Quarantine Fitness</h1>
<ul class='nav'>
    <% if @logged_in_user %>
        <p class="welcome_name">Welcome, <%= @logged_in_user.name %></p> 
        <li><%= link_to "My Profile", user_path(@logged_in_user) %></li>
        <li><%= link_to "All Routines", routines_path %></li>
        <li><%= link_to "Exercise Library", exercises_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <li><%= link_to 'Log-out', logout_path, method: :delete %></li>
    <% else %>
        <li><%= link_to "Log in", new_login_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "All Routines", routines_path %></li>
        <li><%= link_to "Exercise Library", exercises_path %></li>
        <li><%= link_to "About", about_path %></li> 
  <% end %>
</ul>

app/views/exercises/index.html.erb
<%= render 'nav' %>
<h1 class="title">Exercise Library</h1>

<div class="routines-container">
<% @exercises.each do |exercise| %>
<div class="routines-tile">
<p class="center"> <%= link_to exercise.name, exercise_path(exercise) %> </p>
<img class="index" src="<%= exercise.img_url %>">
</div>
<% end %>
</div>

app/views/exercises/show.html.erb
<%= render 'nav' %>

<h1 class="title"><%= @exercise.name %></h1>
<img class="exercise-img" src="<%= @exercise.img_url %>">

<div class="directions-div">
<p class="show-directions"><%= @exercise.directions %></p>
</div>

<hr>

<% if @logged_in_user %>
<div class="add-exercise">
    <h4>Add this Exercise to a Routine</h4>
    <%= form_for @split do |f| %>
        <%= f.label :routines_id %>
        <%= f.collection_select :routine_id, @routines, :id, :name %> 

        <%= f.hidden_field :exercise_id, value: @exercise.id %> 

        <%= f.label :duration, "Seconds"%>
        <%= f.number_field :duration %>
        
        <%= f.submit "Add Exercise"%>
    <% end %>
</div>
    <% end %>

<p><%= link_to "Back to Exercises", exercises_path %></p>

app/views/routines/_form.html.erb
<h4 class="center">
<%= form_for @routine do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, autocomplete: 'off'%>

    <%= f.label :weekday %>
    <%= f.collection_select :weekday, @weekdays, :to_s, :to_s, include_blank: false%>
    
    <%= f.submit %>
<% end %>
</h4> 

app/views/routines/_nav.html.erb
<h1 class="web_name">Quarantine Fitness</h1>
<ul class='nav'>
    <% if @logged_in_user %>
        <p class="welcome_name">Welcome, <%= @logged_in_user.name %></p> 
        <li><%= link_to "My Profile", user_path(@logged_in_user) %></li>
        <li><%= link_to "All Routines", routines_path %></li>
        <li><%= link_to "Exercise Library", exercises_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <li><%= link_to 'Log-out', logout_path, method: :delete %></li>
    <% else %>
        <li><%= link_to "Log in", new_login_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "All Routines", routines_path %></li>
        <li><%= link_to "Exercise Library", exercises_path %></li>
        <li><%= link_to "About", about_path %></li> 
  <% end %>
</ul>

app/views/routines/about.html.erb
<%= render 'nav' %>

<h1 class="title">About Us</h1>

<p class="center about">We are a workout sharing platform that allows you to create and share 
    customized home workout routines that you've been doing during quarantine.</p>

app/views/routines/edit.html.erb
<%= render 'nav' %>
<h1 class="title"> Edit <%= @routine.name %> </h1>
<%= render 'form' %>
    

app/views/routines/index.html.erb
<%= render 'nav' %>

    <h1 class="title">All Routines</h1>

<div class="routines-container">
    
        <% @routines.each do |routine| %>
        <div class="routines-tile"> 
            <p class="center"><%= link_to routine.name, routine_path(routine) %></p>
            <p class="center"> Created by: <strong><%= routine.user.name %></p> </strong>
        </div>
        <% end %>
</div>

app/views/routines/new.html.erb
<%= render 'nav' %>

<h1 class="title"> Create a new Routine </h1>
<%= render 'form' %>

app/views/routines/show.html.erb
<%= render 'nav' %>

<h1 class="title"><%= @routine.name %></h1>

<h4 class="center"><strong>Created by:</strong> <%= @routine.user.name %></h4>

<% if @logged_in_user == @routine.user %>
<h4 class="center"><%= @routine.weekday %></h4>
<div class="center">
    <p><%= button_to "Edit Routine", edit_routine_path(@routine), method: :get %></p>
    <%= button_to 'Delete Routine', routine_path(@routine), method: :delete %>
    </div>
<% end %>

<hr>
<div class="center">
    <% @routine.splits.each do |split| %>
       <p><%= link_to split.exercise.name, exercise_path(split.exercise.id) %> |
        <%= split.duration %> seconds</p> 
            <% if @logged_in_user == @routine.user %>
                <%=button_to "Delete", split_path(split), method: :delete %>
            <% end %>
    <% end %>
</div>

<% if @logged_in_user == @routine.user %>

<hr>
<div class="add-to-routine">
<h3>Add exercises to <%= @routine.name %></h3>
    <%= form_for @split do |f| %>
        <%= f.hidden_field :routine_id, value: @routine.id %>   

        <%= f.label :exercise_id %>
        <%= f.collection_select :exercise_id, @exercises, :id, :name %>

        <%= f.label :duration, "Seconds"%>
        <%= f.number_field :duration %>
    
        <%= f.submit "Add Exercise" %>
    <% end %>
</div>

<% end %>

<h2>Comments:</h2>
<% @routine.comments.each do |comment| %>
    <p> <strong><%= comment.user.name %></strong> <%= comment.comment %></p>
    <% if @logged_in_user == comment.user %>
    <%= button_to 'Delete Comment', comment_path(comment), method: :delete %>
    <% end %>
<% end %>


<% if @logged_in_user %>
<h2>Add Comment:</h2>
<%= form_for @comment do |f| %>
<%= f.label :comment %>
<%= f.text_field :comment %>

<%= f.hidden_field :routine_id, value: @routine.id %>
<%= f.submit %>
<% end %>
<% end %>

app/views/splits/_form.html.erb
<%= form_for @split do |f| %>
    <%= f.label :routine_id %>
    <%= f.collection_select :routine_id, @routines, :id, :name %>

    <%= f.label :exercise_id %>
    <%= f.collection_select :exercise_id, @exercises, :id, :name %>

    <%= f.label :duration, "Seconds"%>
    <%= f.number_field :duration %>
    
    <%= f.submit "Add Exercise" %>
<% end %>

app/views/splits/edit.html.erb
<h1> Add Exercises </h1>
<%= render 'form' %>

app/views/splits/new.html.erb
<h1> Add Exercise to a Routine </h1>
<%= render 'form' %>

app/views/users/_nav.html.erb
<h1 class="web_name">Quarantine Fitness</h1>
<ul class='nav'>
    <% if @logged_in_user %>
        <p class="welcome_name">Welcome, <%= @logged_in_user.name %></p> 
        <li><%= link_to "My Profile", user_path(@logged_in_user) %></li>
        <li><%= link_to "All Routines", routines_path %></li>
        <li><%= link_to "Exercise Library", exercises_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <li><%= link_to 'Log-out', logout_path, method: :delete %></li>
    <% else %>
        <li><%= link_to "Log in", new_login_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "All Routines", routines_path %></li>
        <li><%= link_to "Exercise Library", exercises_path %></li>
        <li><%= link_to "About", about_path %></li> 
  <% end %>
</ul>

app/views/users/new.html.erb
<%= render 'nav' %>
<h1 class="title">Create an Account</h1>

<h4 class="center">
<%= form_for @user do |f| %>
  <%= f.label :name, "Username" %>
  <%= f.text_field :name, autocomplete: 'off' %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>
</h4>

app/views/users/show.html.erb
<%= render 'nav' %>
<h1 class="title">Hello, <%= @user.name %></h1>

<h4 class="center">
<% if @user.routines.any? %>
<p>Here are your routines:</p>
    <% @user.routines.each do |routine| %>
    <%= routine.weekday %> | <%= link_to routine.name, routine_path(routine) %> <br><br>
    <% end %>
    <%= link_to 'Create a New Routine', new_routine_path, class: "btn"%>
<% else %>
    <p>You have no routines yet!</p>
    <%= link_to 'Create a New Routine', new_routine_path, class: "btn" %>
<% end %>
</h4>